# Basic site settings
title: CodePilot

# Theme settings
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Navigation
nav_sort: case_sensitive

# Aux links (shown in upper right)
aux_links:
  "View on GitHub":
    - "https://github.com/setiadeepanshu01/Code-Pilot.git"
    
# Color scheme
color_scheme: light

# Author settings
author:
    name: Deepanshu Setia
    url: https://github.com/setiadeepanshu01
    twitter: setiadeepanshu

# Mermaid settings
mermaid:
  version: "11.6.0"  # Pick the version you want
  # Default configuration
  config: |
    directionLR

# Callouts settings
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  best-practice:
    title: Best Practice
    color: green
  
# The custom navigation
nav:
  - Home: index.md       # Link to your main docs index
  - GitHub: "https://github.com/setiadeepanshu01"
